  # Server
server.port=8083

  # Spring Application
spring.application.name=inventory-service

  # Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb
spring.datasource.username=root
spring.datasource.password=root

  # JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true  

  # Management Endpoints
management.endpoints.web.exposure.include=health,info,metrics

  # Logging
logging.level.com.example.inventoryservice=DEBUG